add og/media card & use prettier to format automatically
Qv2ray/qv2ray.github.io pull request #88
Opened 2021-01-15 18:35 UTC by wallena3

2021-01-15 18:45 UTC, wallena3 commented
使用oss code的prettier默认规则，配合formatOnSave,可以非常方便的统一格式，再不用因为格式的问题检查与花费时间。如果觉得可行我后续补上format全部md文件的commit

2021-01-15 23:54 UTC, DuckSoft commented
Vuepress 的 Markdown 格式对主流的 Formatter 非常不友好，不建议设置。
如果你有支持 Vuepress Markdown 的 Formatter，那么可以考虑。

og/media card is okay.

2021-01-16 01:55 UTC, kidonng commented
- 写格式化配置请一并[推荐插件](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions)。
- 写预置 VSCode 设置不如挂 Git hooks。
- Qv2ray 已经是搜索结果最前列了（排除 GitHub），SEO 没意义。

> Vuepress 的 Markdown 格式对主流的 Formatter 非常不友好，

我记得 Prettier 可以处理。

2021-01-16 01:57 UTC, kidonng requested changes
🤷‍♀️

2021-01-16 02:17 UTC, DuckSoft commented on docs/.vuepress/config.js
> +    }
```suggestion
    'seo': {
      modifiedAt: $page => $page.lastUpdated && new Date($page.lastUpdated),
      siteTitle: _ => '纵使千山多万壑，犹有青鸾踏云间',
      title: _ => 'Qv2ray Official Site',
      description: _ => '跨平台 V2Ray GUI',
      type: _ => 'website',
      url: _ => 'https://qv2ray.net/',
      image: _ => 'https://raw.githubusercontent.com/Qv2ray/Qv2ray/master/assets/icons/qv2ray.png'
    }
```

2021-01-16 02:18 UTC, DuckSoft reviewed
I will leave out the `settings.json` and merge others.

2021-01-16 02:19 UTC, merged

2021-01-16 02:28 UTC, wallena3 commented
Prettier是存在Vuepress的支持的。

>     * 写格式化配置请一并[推荐插件](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions)。
这个pr说的插件就是oss code的Prettier，没太明白这点什么意思？格式化配置就是默认的，没有自定义修改。
>     * 写预置 VSCode 设置不如挂 Git hooks。
我个人觉得能用插件更好，ctrl+s保存时所见即得，不用卡在提交的时候用hook,不过这点观点不同也无所谓。
>     * Qv2ray 已经是搜索结果最前列了（排除 GitHub），SEO 没意义。OG 卡片可以挂，就不用插件了，直接写 header。
这个确实，seo可能的提升只是附属产品，主要是解决消息卡片。我只会用这种插件的方式解决，vuepress应该怎么直接写header？

2021-01-16 02:30 UTC, DuckSoft commented
本仓库的最终决定权和处置权交给 @kidonng。